// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tdpcwuuoggfpbfthhphb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkcGN3dXVvZ2dmcGJmdGhocGhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4OTEyNDAsImV4cCI6MjA3MjQ2NzI0MH0.lt4Lv418T3pbbez6bWOOzRCS9mBDCupXN4qhMfMfdBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);